<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>eedc9051-a9df-4155-9c22-d9ea41d19793</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//img[contains(@src,'https://a.storyblok.com/f/241071/333x53/fbc5cd0971/imagotype.png')])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e0462ba5-5294-4dc5-8fcf-651edca2b4fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://a.storyblok.com/f/241071/333x53/fbc5cd0971/imagotype.png</value>
      <webElementGuid>4952a734-fa61-4696-8932-8e8b5b4cfab3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;flights_search index logged-in&quot;]/header[@class=&quot;header&quot;]/nav[@class=&quot;navbar navbar-light navbar-expand bg-white py-0&quot;]/div[@class=&quot;container-lg px-2 px-sm-auto&quot;]/a[@class=&quot;navbar-brand imagotype&quot;]/div[2]/img[1]</value>
      <webElementGuid>34ec22aa-35bd-4657-a78c-cb7b0809c0c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://a.storyblok.com/f/241071/333x53/fbc5cd0971/imagotype.png')])[2]</value>
      <webElementGuid>c2a4a8dd-b7a8-47b7-90f7-47140e873f05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div[2]/img</value>
      <webElementGuid>fd829ee2-4042-43fd-8b13-44903d2331bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://a.storyblok.com/f/241071/333x53/fbc5cd0971/imagotype.png']</value>
      <webElementGuid>b6f257fa-623c-486d-bc8e-3ca777f27803</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
